version: "3"

services:
  mysql:
    # platform: linux/x86_64
    image: mysql:latest
    container_name: mysql_isucon11q
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
